Repository yt-project/yt_astro_analysis, pull requests merged in 2021-12, with the labels that each got.

#111 only access particle_type field in rockstar if it exists and is needed
  yt_astro_analysis/halo_analysis/halo_finding/rockstar/rockstar_interface.pyx
Labels: enhancement

#113 Fix error message.
  yt_astro_analysis/halo_analysis/halo_finding/rockstar/rockstar.py
Labels: bug

#116 REL: update cibuildwheel, simplify wheel building workflow
  .github/workflows/wheels.yaml
Labels: enhancement

#120 DOC: update/clarify installation instructions
  README.md
Labels: documentation
