Repository yt-project/yt_astro_analysis, pull requests merged in 2022-01, with the labels that each got.

#127 Make sure to initialize index before checking particle types.
  yt_astro_analysis/halo_analysis/halo_finding/rockstar/rockstar.py
Labels: bug

#126 version updates
  CITATION.rst
  README.md
  doc/source/conf.py
  setup.cfg
  yt_astro_analysis/__init__.py
Labels: documentation, infrastructure

#132 BUG: fix broken example with halo plotting
  yt_astro_analysis/halo_analysis/halo_catalog/__init__.py
  yt_astro_analysis/halo_analysis/halo_catalog/plot_modifications.py
Labels: bug

#133 Make total particles a 64 bit integer.
  yt_astro_analysis/halo_analysis/halo_finding/rockstar/rockstar.py
  yt_astro_analysis/halo_analysis/halo_finding/rockstar/rockstar_interface.pyx
Labels: bug

#134 Set output directory properly for rockstar halo finder.
  yt_astro_analysis/halo_analysis/halo_catalog/halo_catalog.py
Labels: bug

#135 Version change and changelog updates for 1.1.1 release.
  doc/source/changelog.rst
  doc/source/conf.py
  setup.cfg
  yt_astro_analysis/__init__.py
Labels: infrastructure

#136 Update version and citation.
  CITATION.rst
  doc/source/conf.py
  setup.cfg
  yt_astro_analysis/__init__.py
Labels: infrastructure
