Repository yt-project/yt_astro_analysis, pull requests merged in 2023-10, with the labels that each got.

#226 BUG: fix usage of deprecated (and removed) clobber argument from astropy
  doc/source/PPVCube.ipynb
Labels: bug

#225 Updated ppv_cube.py to avoid deprecated function 'update_all_headers'
  yt_astro_analysis/ppv_cube/ppv_cube.py
Labels: bug

#228 BUG: fix a couple bugs in PPVCube notebook
  doc/source/PPVCube.ipynb
Labels: bug, documentation

#235 DOC: pin doc requirements
  .readthedocs.yml
  doc/requirements.txt
Labels: bug, documentation

#237 DOC: upgrade sphinx to latest version and enable automated upgrades for doc dependencies
  .circleci/config.yml
  .github/dependabot.yml
  .readthedocs.yml
  requirements/docs.txt
  requirements/tests.txt
Labels: documentation, dependencies
